services:
  db:
    image: pgvector/pgvector:pg17 
    container_name: pgvector-db
    environment:
      POSTGRES_USER: YOUR_USER
      POSTGRES_PASSWORD: YOUR_PASSWORD
      POSTGRES_DB: smarthire
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: 